name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalar dependencias
        run: npm ci
      - name: Ejecutar ESLint
        run: npm run lint
      - name: Ejecutar Prettier (solo chequeo)
        run: npx prettier --check .
